# Generated by Django 2.2.5 on 2019-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentnotification',
            name='title',
            field=models.TextField(default='TEST'),
            preserve_default=False,
        ),
    ]
