packageExtensions:
  html-webpack-inline-svg-plugin@2.2.6:
    peerDependencies:
      html-webpack-plugin: 4.3.0
  webpack-pwa-manifest@4.2.0:
    peerDependencies:
      html-webpack-plugin: 4.3.0

yarnPath: .yarn/releases/yarn-2.2.2.cjs
