# Generated by Django 2.2.5 on 2019-10-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55)], default=5),
            preserve_default=False,
        ),
    ]
