# Generated by Django 2.2.5 on 2019-10-04 07:28

from django.db import migrations, models
import catalpa_wagtail_tools.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0002_auto_20191004_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='lessonpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='lessonpage',
            name='duration',
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='content_aim',
            field=models.TextField(blank=True, default='Start learning by digging deeper into the content'),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='content_cards',
            field=wagtail.core.fields.StreamField([('content', catalpa_wagtail_tools.blocks.ContentBlock())], default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='content_duration',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='content_title',
            field=models.CharField(default='Content', max_length=128),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='jobs',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.ChoiceBlock(choices=[('business_owner', 'Business Owner'), ('engineer', 'Engineer'), ('builder', 'Builder')]))], default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='objective_aim',
            field=models.TextField(blank=True, default="Discover what we're aiming to learn in this lesson"),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='objective_cards',
            field=wagtail.core.fields.StreamField([('title_description', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=32)), ('description', wagtail.core.blocks.TextBlock(max_length=512))]))], default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='objective_duration',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='objective_title',
            field=models.CharField(default='Objective', max_length=128),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='test_aim',
            field=models.TextField(blank=True, default='Take a quiz to test your knowledge and finalise this lesson'),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='test_cards',
            field=wagtail.core.fields.StreamField([('multiple_choice', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(max_length=256)), ('answers', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=64)), ('correct', wagtail.core.blocks.BooleanBlock(default=False))])))]))], default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='test_duration',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='test_title',
            field=models.CharField(default='Test Knowledge', max_length=128),
        ),
    ]
