# Generated by Django 2.2.5 on 2019-10-07 00:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0003_auto_20191004_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='jobs',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.ChoiceBlock(choices=[('business_owner', 'Business Owner'), ('engineer', 'Engineer'), ('builder', 'Builder')]))], blank=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='test_cards',
            field=wagtail.core.fields.StreamField([('multiple_choice', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(max_length=256)), ('answers', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=64)), ('correct', wagtail.core.blocks.BooleanBlock(default=False, required=False))])))]))]),
        ),
    ]
