# Generated by Django 2.2.5 on 2019-10-22 00:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0007_rename_choice_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='content_cards',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='objective_cards',
            field=wagtail.core.fields.StreamField([('title_description', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=32)), ('description', wagtail.core.blocks.TextBlock(max_length=512))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='test_cards',
            field=wagtail.core.fields.StreamField([('single_choice', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(max_length=256)), ('answers', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=64)), ('correct', wagtail.core.blocks.BooleanBlock(default=False, required=False))])))]))], blank=True, null=True),
        ),
    ]
