# Generated by Django 2.2.5 on 2019-12-03 04:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0009_auto_20191121_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='jobs',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.ChoiceBlock(choices=[('business_owner', 'Business Owner'), ('engineer', 'Engineer'), ('builder', 'Builder'), ('tourism_hospitality_retail_manager', 'Tourism, Hospitality, and Retail Manager'), ('communications_and_marketing_specialist', 'Communications and Marketing Specialist'), ('banking_and_finance_associate', 'Banking and Finance Associate')]))], blank=True),
        ),
    ]
