# Generated by Django 2.2.5 on 2020-02-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0010_new_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='\n        Publish this page as "Coming Soon". Students will see this page\'s\n        overview, but won\'t be able to access its objectives, content, or\n        test.'),
        ),
    ]
