# Generated by Django 2.2.5 on 2020-03-30 05:44

import catalpa_wagtail_tools.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_content', '0011_lessonpage_coming_soon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='content_cards',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('video', catalpa_wagtail_tools.blocks.MediaBlock())]),
        ),
    ]
